; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = waveshare_esp32_s3_lcd_2

[env:waveshare_esp32_s3_lcd_2]
platform = espressif32
board = waveshare_esp32_s3_lcd_2
framework = arduino
; platform_packages = framework-arduinoespressif32 @ symlink://C:/PIO_Cores/esp32-bluepad32-4.1.0
platform_packages = framework-arduinoespressif32 @ https://github.com/maxgerhardt/pio-framework-bluepad32/archive/refs/heads/main.zip
board_build.arduino.upstream_packages = no
monitor_speed = 115200
board_build.partitions = default_16MB.csv
board_build.arduino.memory_type = qio_opi
build_flags = 
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D HAS_BLUEPAD32=1
    -D HAS_WIFI_SERIAL=1
    -L.pio/libdeps/waveshare_esp32_s3_lcd_2/micro_ros_arduino/src/esp32/
    -lmicroros
lib_deps =
    https://github.com/micro-ROS/micro_ros_arduino.git#humble
lib_ldf_mode = chain+
test_build_src = yes
